const GET_PROPERTY = "GET_PROPERTY";
const GET_PROPERTY_DETAIL = "GET_PROPERTY_DETAIL";
const CLEAN_DETAIL = "CLEAN_DETAIL";
const ADD_USER = "ADD_USER";
const CREATE_PROPERTY = "CREATE_PROPERTY";
const ERROR = "ERROR";
const USER_LOGIN = "USER_LOGIN";
const FILTERS = "FILTERS";
const PROPERTY_EDITED = "PROPERTY_EDITED";
const CREATE_BOOKING = "CREATE_BOOKING";
const GET_ALL_BOOKINGS = "GET_ALL_BOOKINGS";
const GET_BOOKING = "GET_BOOKING";
const GET_ALL_USERS = "GET_ALL_USERS";
const USER_EDITED = "USER_EDITED";
const USER_LOGOUT = "USER_LOGOUT";
const RESET_STATE = "RESET_STATE";
const PROPERTY_DAYS_EDITED = "PROPERTY_DAYS_EDITED";
const SAVE_PROPERTY = "SAVE_PROPERTY";
const REMOVE_FROM_SAVED = "REMOVE_FROM_SAVED";
const USER_AUTHENTICATED = "USER_AUTHENTICATED";
const DELETE_PROPERTY = "DELETE_PROPERTY";
const USER_BY_ID = "USER_BY_ID";

export {
	USER_BY_ID,
	DELETE_PROPERTY,
	USER_AUTHENTICATED,
	FILTERS,
	GET_PROPERTY,
	GET_PROPERTY_DETAIL,
	CLEAN_DETAIL,
	ADD_USER,
	CREATE_PROPERTY,
	ERROR,
	USER_LOGIN,
	PROPERTY_EDITED,
	CREATE_BOOKING,
	GET_ALL_BOOKINGS,
	GET_BOOKING,
	GET_ALL_USERS,
	USER_EDITED,
	USER_LOGOUT,
	RESET_STATE,
	PROPERTY_DAYS_EDITED,
	SAVE_PROPERTY,
	REMOVE_FROM_SAVED,
};
