const GET_PROPERTIES = "GET_PROPERTIES";
const GET_PROPERTY_DETAIL = "GET_PROPERTY_DETAIL";
const CLEAN_DETAIL = "CLEAN_DETAIL";
const ADD_USER = "ADD_USER";
const USER_LOGIN = "USER_LOGIN";
const ADD_PROPERTY = "ADD_PROPERTY";
const CLEAN_FILTERS = "CLEAN_FILTERS";
const ERROR = "ERROR";

export {
	GET_PROPERTIES,
	GET_PROPERTY_DETAIL,
	CLEAN_DETAIL,
	ADD_USER,
	USER_LOGIN,
	ADD_PROPERTY,
	CLEAN_FILTERS,
	ERROR,
};
